version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34.6
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: mysecret42
        port: 4466
        databases:
          default:
            connector: postgres
            host: db
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres: