version: '3'
services:
  todo-app:
    build: .
    image: todo-app
    ports:
    - "3000:3000"
    links:
    - todo-redis
  todo-redis:
    image: redis:5
    ports:
    - "6379:6379"
    volumes:
      - "my-app-data:/data"

volumes:
  my-app-data:
