version: "2"

volumes:
  gitea-data:
    external:
      name: gitea-data
  gitea-config:
    external:
      name: gitea-config

services:
  gitea:
    image: gitea/gitea:1.15.6-rootless
    restart: always
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
