version: "3"

networks:
  gitea:
    external: false

volumes:
    gitea:
      external: true
    postgres:
      external: true
    pgadmin_data:
      external: true

services:
  dns-proxy:
    image: defreitas/dns-proxy-server
    hostname: dns_proxy
    container_name: dns_proxy
    ports:
      - '5380:5380'
    networks:
      - gitea
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf  
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=<supersecretpassword>
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
    ports:
      - "3000:3000"
      - "10022:22"
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=<supersecretpassword>
      - POSTGRES_DB=gitea
    ports:
      - "5432:5432"
    networks:
      - gitea
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=someone@somewhere.com
      - PGADMIN_DEFAULT_PASSWORD=<supersecretpassword>
    networks:
      - gitea
    ports:
      - "10080:80"
    volumes: 
      - pgadmin_data:/var/lib/pgadmin
